### ISSUE TITLE
Materials appear under the fish tab in inventory

### ISSUE THREAD

**Issue by Timo654** [GarnetSunset/Ishin-Machine-Translation#4]
Materials appear under the fish tab in inventory
[Example](https://cdn.discordapp.com/attachments/696000822735273994/826070252801753128/IMG_20210329_142759.jpg)

**Comment by Nydrogen** [comment]
I think that i found a fix,It seems to work so far.

That's another issue caused by the EBOOT.

The code causing the issue (open in a hex editor):
[Eboot - Materials appear under the fish tab in inventory CAUSE.txt](https://github.com/GarnetSunset/Ishin-Machine-Translation/files/7028339/Eboot.-.Materials.appear.under.the.fish.tab.in.inventory.CAUSE.txt)

The code fixing the issue:
[Eboot - Materials appear under the fish tab in inventory FIX.txt](https://github.com/GarnetSunset/Ishin-Machine-Translation/files/7028340/Eboot.-.Materials.appear.under.the.fish.tab.in.inventory.FIX.txt)
